version: '3'

tasks:
  test:
    desc: Run all tests
    cmds:
      - go test ./...

  cover:
    desc: Run tests with coverage and show summary
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  cover-html:
    desc: Run tests with coverage and open HTML report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  validate:
    desc: Run both tests and linter
    cmds:
      - task: lint
      - task: test
