version: '3'

tasks:
  test:
    desc: Run all tests
    cmds:
      - go test ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  validate:
    desc: Run both tests and linter
    cmds:
      - task: lint
      - task: test
